Add /vanished command
PGMDev/Community pull request #56
Opened 2024-02-08 05:52 UTC by zzufx

Allows you to see a list of online vanished players, much like `/nicks` does with nicked players.

2024-02-10 01:37 UTC, applenick requested changes
Looks good. Always happy to see new commands, though unsure if this belongs in Community or should be directly in PGM. As we transitioned vanish completely out of Community a while ago in favor of the PGM implementation. @Pablete1234, any thoughts?

https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/command/VanishCommand.java

https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/integrations/SimpleVanishIntegration.java

2024-02-10 01:37 UTC, applenick commented on src/main/java/dev/pgm/community/commands/VanishedCommand.java
> +  @CommandMethod("vanished|lv|listv")
I'd probably avoid `lv` and `listv`, just `/vanished` for simplicity.

2024-02-10 01:40 UTC, applenick commented on src/main/java/dev/pgm/community/commands/VanishedCommand.java
> +            .filter(player -> player.hasMetadata("isVanished"))
Also probably better to use
```suggestion
            .filter(Integration::isVanished)
```

2024-02-10 15:33 UTC, Pablete1234 commented
> As we transitioned vanish completely out of Community a while ago in favor of the PGM implementation. @Pablete1234, any thoughts?

I don't mind this, while pgm has a (default) vanish implementation others can still change the impl, and this command being on community is fine by me, it's not really an "important/must-have" command for pgm, it's at most a nice-to-have which i'm fine existing in either pgm or community

2024-02-10 19:31 UTC, applenick commented
Awesome! Thanks @Pablete1234 

@zzufx When you have a chance could you double check your commit is fully signed. Then we can merge, thanks!

2024-02-10 19:31 UTC, applenick approved these changes

2024-02-11 00:39 UTC, zzufx commented
> @zzufx When you have a chance could you double check your commit is fully signed. Then we can merge, thanks!

Whoops, sorry about that, should be good to go now!

2024-02-12 23:17 UTC, merged