Update to Cloud v2.0
PGMDev/Community pull request #59
Opened 2024-05-18 02:00 UTC by calcastor

WIP update to Cloud 2.0, depends on https://github.com/PGMDev/PGM/pull/1319

I removed the confirmation manager like we did in https://github.com/PGMDev/PGM/pull/1319 but let me know if this should be maintained.

Currently untested beyond ensuring it builds against the aforementioned PGM PR.

2024-06-11 07:21 UTC, applenick requested changes

2024-06-11 07:21 UTC, applenick commented on pom.xml
> +        </repository>
repo.pgm.fyi should be updated now, remove this when you get a chance 👍 
```suggestion

```

2024-06-11 23:32 UTC, applenick approved these changes
> I removed the confirmation manager like we did in https://github.com/PGMDev/PGM/pull/1319 but let me know if this should be maintained.

To answer this question, I don't believe we used it anywhere so totally fine to remove 👍 

@calcastor Everything looks good! Before merging, I'll do some local testing myself. Have you had a chance to test this further since the initial opening of the PR? While I doubt there will be any issues, it's always a good practice to double-check.

2024-06-12 04:20 UTC, calcastor commented
> > I removed the confirmation manager like we did in [PGMDev/PGM#1319](https://github.com/PGMDev/PGM/pull/1319) but let me know if this should be maintained.
> 
> To answer this question, I don't believe we used it anywhere so totally fine to remove 👍
> 
> @calcastor Everything looks good! Before merging, I'll do some local testing myself. Have you had a chance to test this further since the initial opening of the PR? While I doubt there will be any issues, it's always a good practice to double-check.

I have not unfortunately as I do not have a database set up at the moment.

2024-06-12 07:34 UTC, merged